completed dynamic js card and js modal
jubaer919/Portfolio pull request #13
Opened 2023-04-19 18:33 UTC by jubaer919

- I use a JavaScript array to store all of the information for all projects.
- For each project I store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
- I update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.

2023-04-19 18:46 UTC, AdnanOlarmmi requested changes
Hi @jubaer919 😊,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request 🆘💀
You have submitted a project, that you created the project by yourself without involving your partner, so please can you make your partner commit to the project 😃 as this is pair programming activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-04-20 09:33 UTC, wayungi requested changes
Hi @jubaer919 , 

![image](https://user-images.githubusercontent.com/99656687/224543672-ce29b4b2-d478-447f-ae6f-eb3df4f35902.png)

**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Correct GitHub flow 👍🏾 
- [ ] Modal can close & open 👍🏾 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 09:33 UTC, wayungi commented on app.js
> +// });
- [ ] Kindly remove all this commented code and all other occurrences of commented code in your code base. commented code makes your repository dirty 👍🏾

2023-04-20 09:33 UTC, wayungi commented on app.js
> +    cardCta1.innerText = 'See live';
- [ ] Your `see live` & `see source` button do not have the icons as in the Figma
**your implementaton**
![btns](https://user-images.githubusercontent.com/99656687/233315106-cab2cbca-dac3-4a99-8b9f-397edf754fb5.png)
**figma**
![btn1](https://user-images.githubusercontent.com/99656687/233315380-fded8c39-56c0-4b34-8fd2-87a21736b635.png)

2023-04-20 09:33 UTC, wayungi commented on style.css
> +}
- [ ] Please remember to delete the comment on line 430

- [ ] I suggest making the popup fit the mobile and desktop sizes properly without the need to scroll. 

- [ ] To match the Figma, the modal overlay need to have a **[blur](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur)**. 
![modal](https://user-images.githubusercontent.com/99656687/233322912-d36d6f94-4028-4794-8e49-bce1e6f2488d.png)

2023-04-20 09:33 UTC, wayungi commented on app.js
> +}
- [ OPTIONAL]  kindly avoid very large functions. You can always break functions into small manageable parts. Large functions are hard to maintain and debug. What do you think 🤔 ?

2023-04-20 09:36 UTC, wayungi commented
@jubaer919, if anything is not clear,  for even a quicker response, please reach me on Slack or zoom

2023-04-20 17:25 UTC, LionRouge1 requested changes
Hi @jubaer919, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-20 17:25 UTC, LionRouge1 commented on style.css
> +}
- [ ] As mentioned in the previous review, the popup windows overlay needs to have `backdrop-filter: blur(4px)` and use `background-color: #c1c7d0ab` (the values that are given to these CSS properties can be changed according to your will but just make sure the popup looks exactly like the Figma design) for the background colour to match the Figma design.

### Your design :point_down: 
![Screenshot from 2023-04-20 17-01-35](https://user-images.githubusercontent.com/91142432/233437102-aa1612d4-050a-4ee5-b379-b9d8e1fa607a.png)

### Figma's Design :point_down: 
![Screenshot from 2023-04-19 13-38-59](https://user-images.githubusercontent.com/91142432/233437175-c30b42b1-be9a-4466-8d77-74a6112fd717.png)

2023-04-20 17:25 UTC, LionRouge1 commented on style.css
> +}
- [ ] Kindly reduce the padding of the popup windows on the mobile version(see image) to follow the Figma design.

### Your Design :point_down: 
![Screenshot from 2023-04-20 17-03-43](https://user-images.githubusercontent.com/91142432/233438887-c34929c8-1bc3-4265-8636-6b904011064f.png)

### Figma's Design :point_down: 
![Screenshot from 2023-04-19 13-30-07](https://user-images.githubusercontent.com/91142432/233438946-8b9f7cd1-87e9-4b79-bf4e-e72868a4fea6.png)

2023-04-20 17:25 UTC, LionRouge1 commented on style.css
> +  justify-content: center; */
- [ ] As mentioned by the previous reviewer, remove all commented code from your codebase. They make your project look messy.

2023-04-20 17:25 UTC, LionRouge1 commented on app.js
> +}
[OPTIONAL]
- [ ] Kindly take optional comments into account as they can make your code better. It would be adequate if you break this function into small parts for better maintainability and debugging.

2023-04-20 18:06 UTC, binhussen approved these changes
Hi @jubaer919 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 03:33 UTC, merged